# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WallArtGenerate.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 245)
        MainWindow.setStyleSheet("background-color: rgb(175, 181, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(152, 116, 91);\n"
"font: 16pt \"Sitka\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadImageButton.setGeometry(QtCore.QRect(50, 140, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loadImageButton.setFont(font)
        self.loadImageButton.setStyleSheet("background-color: rgb(182, 82, 24);")
        self.loadImageButton.setObjectName("loadImageButton")
        self.loadPaletteButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadPaletteButton.setGeometry(QtCore.QRect(250, 140, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loadPaletteButton.setFont(font)
        self.loadPaletteButton.setStyleSheet("background-color: rgb(182, 82, 24);")
        self.loadPaletteButton.setObjectName("loadPaletteButton")
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setGeometry(QtCore.QRect(50, 50, 381, 81))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.generateButton.setFont(font)
        self.generateButton.setStyleSheet("background-color: rgb(182, 82, 24);")
        self.generateButton.setObjectName("generateButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WALL ART GENERATOR"))
        self.loadImageButton.setText(_translate("MainWindow", "LOAD IMAGE"))
        self.loadPaletteButton.setText(_translate("MainWindow", "LOAD PALETTE"))
        self.generateButton.setText(_translate("MainWindow", "GENERATE"))
