# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WallArtGenerate.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(526, 354)
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setStyleSheet("background-color: rgb(251, 248, 244);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 75 20pt \"Candara\";\n"
"color:#ab926f;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadImageButton.setGeometry(QtCore.QRect(90, 30, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.loadImageButton.setFont(font)
        self.loadImageButton.setStyleSheet("background-color: #ab926f;\n"
"color: rgb(251, 248, 244);")
        self.loadImageButton.setObjectName("loadImageButton")
        self.loadPaletteButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadPaletteButton.setGeometry(QtCore.QRect(290, 30, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.loadPaletteButton.setFont(font)
        self.loadPaletteButton.setStyleSheet("background-color: #ab926f;\n"
"color: rgb(251, 248, 244);")
        self.loadPaletteButton.setObjectName("loadPaletteButton")
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setGeometry(QtCore.QRect(90, 220, 381, 81))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.generateButton.setFont(font)
        self.generateButton.setStyleSheet("background-color: rgb(151, 94, 89);\n"
"font: 75 32pt \"Candara\";\n"
"color: rgb(251, 248, 244);\n"
"\n"
"")
        self.generateButton.setObjectName("generateButton")
        self.block_size = QtWidgets.QPushButton(self.centralwidget)
        self.block_size.setGeometry(QtCore.QRect(90, 90, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.block_size.setFont(font)
        self.block_size.setStyleSheet("background-color: #ab926f;\n"
"color: rgb(251, 248, 244);")
        self.block_size.setObjectName("block_size")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 160, 321, 31))
        self.label.setStyleSheet("color: #ab926f;\n"
"font: 75 15pt \"Candara\";")
        self.label.setObjectName("label")
        self.select_format = QtWidgets.QComboBox(self.centralwidget)
        self.select_format.setGeometry(QtCore.QRect(360, 170, 151, 21))
        self.select_format.setStyleSheet("color: #ab926f;\n"
"font: 75 15pt \"Candara\";")
        self.select_format.setObjectName("select_format")
        self.select_format.addItem("")
        self.select_format.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(380, 90, 91, 51))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WALL ART GENERATOR"))
        self.loadImageButton.setText(_translate("MainWindow", "LOAD IMAGE"))
        self.loadPaletteButton.setText(_translate("MainWindow", "LOAD PALETTE"))
        self.generateButton.setText(_translate("MainWindow", "GENERATE"))
        self.block_size.setText(_translate("MainWindow", "ENTER BLOCK SIZE"))
        self.label.setText(_translate("MainWindow", "SELECT THE IMAGE SAVING FORMAT:"))
        self.select_format.setItemText(0, _translate("MainWindow", ".xlsx"))
        self.select_format.setItemText(1, _translate("MainWindow", ".txt"))
